name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: error
          description: Build failed.
          details: 'commit ${{ github.sha }} by ${{ github.actor }} broke the build.'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}          
  #Okay, so have to check all commits that are linked to the push event, because a pull request can contain multiple commits and the PR body text does is not associated?
  tag_release:
    needs: [build]    
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip')}}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:  
    - uses: actions/checkout@v4
    - name: Bump version and push tag      
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch        
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    needs: tag_release
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies 
        run: npm install        
      - name: Build
        run: npm run build
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}     
      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: A new version of Pokedex deployed.
          details: 'to: https://fly.io/apps/jk-pokedex by ${{ github.actor }}'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
                 