name: Statuscheck

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping_the_app:
    runs-on: ubuntu-20.04
    steps:
      - name: Pokedex healthcheck
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://jk-pokedex.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true